### ISSUE TITLE
Cassandra 4.0-beta 2 is out

### ISSUE THREAD

**Issue by lapo-luchini** [polo-language/cassandra4#1]
Just a heads-up that beta 2 is out. =)

**Comment by polo-language** [comment]
Just submitted the update to 3.11.8. This one will be next!

**Comment by lapo-luchini** [comment]
Uh, [I see](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250005), nice!
I didn't think you would release 3.11.8, as the port is currently marked as [expired in 2020-09-15](https://www.freshports.org/databases/cassandra3/).
(but I'm grateful, as I'm a bit scared to upgrade to 4 while it is in beta, even though it should already be as stable as 3.11 is I guess)

**Comment by polo-language** [comment]
Submitted a patch to update to 4.0-beta2:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250167

**Comment by polo-language** [comment]
4.0-beta2 is now available on the latest ports tree.
